services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'movies'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
