springdoc:
  swagger-ui:
    path: /documentation
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 8080

application:
  client:
    omdb-service:
      url: http://www.omdbapi.com/
      apiSecretKey: a8a42bee

